import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import { auth } from "@/auth";
import { getUserDocuments } from "@/lib/db";
import { vectorStore } from "@/lib/vector-store";

export async function POST(req: NextRequest) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured in .env.local" },
        { status: 500 }
      );
    }

    const session = await auth();
    const user = session?.user;
    if (!user || !user.email) {
      return NextResponse.json({ error: "Non authentifié" }, { status: 401 });
    }

    const userId = (user as any).id;
    const body = await req.json();
    const { messages, studyContext } = body;

    if (!messages || !Array.isArray(messages)) {
      return NextResponse.json(
        { error: "Invalid or missing messages in request body" },
        { status: 400 }
      );
    }

    if (!studyContext) {
      return NextResponse.json(
        { error: "Missing studyContext in request body" },
        { status: 400 }
      );
    }

    const allDocs = await getUserDocuments(userId);
    const activeDocs = allDocs.filter((d: any) => d.toggled);

    let documentReferenceText = "";

    if (activeDocs.length > 0) {
      try {
        const lastUserMessage = [...messages].reverse().find((m) => m.role === "user");
        if (lastUserMessage) {
          const ai = new GoogleGenAI({ apiKey });
          // 1. Embed user query
          const embedRes = await ai.models.embedContent({
            model: "text-embedding-004",
            contents: lastUserMessage.content,
          });

          const values = embedRes.embeddings?.[0]?.values;
          if (values) {
            // 2. Perform similarity search in Vector DB
            const results = await vectorStore.similaritySearch(userId, values, 6);
            
            // 3. Filter chunks to only include active/toggled documents
            const activeDocIds = new Set(activeDocs.map((d: any) => d.id));
            const filteredResults = results.filter((r) => activeDocIds.has(r.docId)).slice(0, 4);

            if (filteredResults.length > 0) {
              documentReferenceText = [
                "--- DEBUT DOCUMENTS DE RÉFÉRENCE DE L'ÉTUDIANT ---",
                "Voici les extraits les plus pertinents de vos documents de cours officiels. Servez-vous de ces extraits pour répondre de façon ciblée et exacte :",
                "",
                filteredResults.map((r, i) => `[Fichier: ${r.metadata?.fileName || "Polycopié"} | Extrait #${i+1}]\n${r.text}`).join("\n\n---\n\n"),
                "--- FIN DOCUMENTS DE RÉFÉRENCE ---"
              ].join("\n");
            }
          }
        }
      } catch (err) {
        console.error("Failed to retrieve RAG context:", err);
      }
    }

    const ai = new GoogleGenAI({ apiKey });

    const systemInstruction = [
      "You are an elite academic AI tutor on the mgscholar.ai platform, specifically tailored for Moroccan university students.",
      "",
      "Student Academic Context:",
      `- University: ${studyContext.universityLabel}`,
      `- Faculty / Branch / Major: ${studyContext.branchLabel}`,
      `- Semester Level: Semestre ${studyContext.semester}`,
      `- Current Module / Subject: ${studyContext.subjectLabel}`,
      "",
      documentReferenceText,
      "",
      "Guidelines for your responses:",
      "1. Language & Tone: Always respond in clear, academic French. Maintain a professional, encouraging, and educational tone.",
      "2. Academic Rigor: Provide structured, exam-oriented responses. Use bullet points, bold key terms, and refer to standard university modules. If the subject is law (droit), refer to Moroccan legal codes (e.g., Code de commerce, Dahir des obligations et des contrats - DOC) where appropriate.",
      "3. Contextual Relevance: Keep your explanations aligned with typical Moroccan higher education syllabus expectations for the selected module.",
      "4. Reference Documents: If reference documents are provided above, read their content carefully. Answer the student's questions by strictly adhering to the facts, structures, and definitions in those documents. Mention which document you are referencing in your reply (e.g., 'D'après votre polycopié [NomDuFichier]...').",
      "5. Formatting: Use markdown (bolding, lists, and tables) to make your answers easy to read and study from.",
    ].join("\n");

    const contents = messages.map((m: { role: string; content: string }) => ({
      role: m.role === "user" ? "user" : "model",
      parts: [{ text: m.content }],
    }));

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents,
      config: {
        systemInstruction,
        temperature: 0.7,
      },
    });

    const replyText = response.text || "No response generated by the model.";

    return NextResponse.json({ text: replyText });
  } catch (error: any) {
    console.error("Error in Gemini chat API:", error);
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}
