import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import { getAuthenticatedUser } from "@/lib/auth";
import { getUserDocuments } from "@/lib/db";

export async function POST(req: NextRequest) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured in .env.local" },
        { status: 500 }
      );
    }

    const user = await getAuthenticatedUser(req);
    if (!user) {
      return NextResponse.json({ error: "Non authentifié" }, { status: 401 });
    }

    const body = await req.json();
    const { messages, studyContext } = body;

    if (!messages || !Array.isArray(messages)) {
      return NextResponse.json(
        { error: "Invalid or missing messages in request body" },
        { status: 400 }
      );
    }

    if (!studyContext) {
      return NextResponse.json(
        { error: "Missing studyContext in request body" },
        { status: 400 }
      );
    }

    const allDocs = await getUserDocuments(user.id);
    const activeDocs = allDocs.filter((d: any) => d.toggled);

    const documentReferenceText = activeDocs.length > 0 
      ? [
          "--- DEBUT DOCUMENTS DE RÉFÉRENCE DE L'ÉTUDIANT ---",
          "Voici le contenu des documents/polycopiés chargés par l'étudiant. Utilisez ces textes en priorité absolue comme base de connaissances pour répondre aux questions, citer des passages, et structurer vos explications académiques :",
          "",
          activeDocs.map((d: any) => `[Fichier: ${d.name}]\n${d.content}`).join("\n\n---\n\n"),
          "--- FIN DOCUMENTS DE RÉFÉRENCE ---"
        ].join("\n")
      : "";

    const ai = new GoogleGenAI({ apiKey });

    const systemInstruction = [
      "You are an elite academic AI tutor on the mgscholar.ai platform, specifically tailored for Moroccan university students.",
      "",
      "Student Academic Context:",
      `- University: ${studyContext.universityLabel}`,
      `- Faculty / Branch / Major: ${studyContext.branchLabel}`,
      `- Semester Level: Semestre ${studyContext.semester}`,
      `- Current Module / Subject: ${studyContext.subjectLabel}`,
      "",
      documentReferenceText,
      "",
      "Guidelines for your responses:",
      "1. Language & Tone: Always respond in clear, academic French. Maintain a professional, encouraging, and educational tone.",
      "2. Academic Rigor: Provide structured, exam-oriented responses. Use bullet points, bold key terms, and refer to standard university modules. If the subject is law (droit), refer to Moroccan legal codes (e.g., Code de commerce, Dahir des obligations et des contrats - DOC) where appropriate.",
      "3. Contextual Relevance: Keep your explanations aligned with typical Moroccan higher education syllabus expectations for the selected module.",
      "4. Reference Documents: If reference documents are provided above, read their content carefully. Answer the student's questions by strictly adhering to the facts, structures, and definitions in those documents. Mention which document you are referencing in your reply (e.g., 'D'après votre polycopié [NomDuFichier]...').",
      "5. Formatting: Use markdown (bolding, lists, and tables) to make your answers easy to read and study from.",
    ].join("\n");

    const contents = messages.map((m: { role: string; content: string }) => ({
      role: m.role === "user" ? "user" : "model",
      parts: [{ text: m.content }],
    }));

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents,
      config: {
        systemInstruction,
        temperature: 0.7,
      },
    });

    const replyText = response.text || "No response generated by the model.";

    return NextResponse.json({ text: replyText });
  } catch (error: any) {
    console.error("Error in Gemini chat API:", error);
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}
