import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

export async function POST(req: NextRequest) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured in .env.local" },
        { status: 500 }
      );
    }

    const body = await req.json();
    const { messages, studyContext } = body;

    if (!messages || !Array.isArray(messages)) {
      return NextResponse.json(
        { error: "Invalid or missing messages in request body" },
        { status: 400 }
      );
    }

    if (!studyContext) {
      return NextResponse.json(
        { error: "Missing studyContext in request body" },
        { status: 400 }
      );
    }

    const ai = new GoogleGenAI({ apiKey });

    // Build specialized system instructions based on the student's university context
    const systemInstruction = [
      "You are an elite academic AI tutor on the mgscholar.ai platform, specifically tailored for Moroccan university students.",
      "",
      "Student Academic Context:",
      `- University: ${studyContext.universityLabel}`,
      `- Faculty / Branch / Major: ${studyContext.branchLabel}`,
      `- Current Module / Subject: ${studyContext.subjectLabel}`,
      "",
      "Guidelines for your responses:",
      "1. Language & Tone: Always respond in clear, academic French. Maintain a professional, encouraging, and educational tone.",
      "2. Academic Rigor: Provide structured, exam-oriented responses. Use bullet points, bold key terms, and refer to standard university modules. If the subject is law (droit), refer to Moroccan legal codes (e.g., Code de commerce, Dahir des obligations et des contrats - DOC) where appropriate.",
      "3. Contextual Relevance: Keep your explanations aligned with typical Moroccan higher education syllabus expectations for the selected module.",
      "4. Formatting: Use markdown (bolding, lists, and tables) to make your answers easy to read and study from.",
    ].join("\n");

    // Format conversation history for the Gemini SDK
    // Gemini expects contents to be: [{ role: 'user' | 'model', parts: [{ text: '...' }] }]
    const contents = messages.map((m: { role: string; content: string }) => ({
      role: m.role === "user" ? "user" : "model",
      parts: [{ text: m.content }],
    }));

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents,
      config: {
        systemInstruction,
        temperature: 0.7,
      },
    });

    const replyText = response.text || "No response generated by the model.";

    return NextResponse.json({ text: replyText });
  } catch (error: any) {
    console.error("Error in Gemini chat API:", error);
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}
